services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: amqp://admin:admin@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production_control
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minioadmin123
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/production_control
    depends_on:
      - minio
      - postgres
      - rabbitmq
      - redis
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:16-alpine
    container_name: production_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production_control
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A src.celery_app worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minioadmin123
      CELERY_BROKER_URL: amqp://admin:admin@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/production_control
    volumes:
      - ./src:/app/src
    restart: unless-stopped
  celery_beat:
    build: .
    command: celery -A src.celery_app.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - celery_worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  flower:
    image: mher/flower:latest
    container_name: flower_dashboard
    working_dir: /app
    command: celery -A src.celery_app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app


volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  minio_data: