"""Add comments

Revision ID: 1c8f214de4f4
Revises: a898f64f6e0d
Create Date: 2026-07-14 12:31:14.801737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8f214de4f4'
down_revision: Union[str, Sequence[str], None] = 'a898f64f6e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'id',
               existing_type=sa.INTEGER(),
               comment='Внутренний ID партии (технический)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('batches', 'is_closed',
               existing_type=sa.BOOLEAN(),
               comment='Статус задания: False - в работе, True - завершено',
               existing_nullable=False)
    op.alter_column('batches', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Точное время, когда партию завершили',
               existing_nullable=True)
    op.alter_column('batches', 'task_description',
               existing_type=sa.VARCHAR(),
               comment='Текстовое описание: что именно нужно сделать',
               existing_nullable=False)
    op.alter_column('batches', 'shift',
               existing_type=sa.VARCHAR(),
               comment="Название или номер смены (например, 'Ночная' или 'Смена 1')",
               existing_nullable=False)
    op.alter_column('batches', 'team',
               existing_type=sa.VARCHAR(),
               comment="Кто выполняет работу (например, 'Бригада 1')",
               existing_nullable=False)
    op.alter_column('batches', 'batch_number',
               existing_type=sa.INTEGER(),
               comment='Производственный номер партии (как в 1С или на бумаге)',
               existing_nullable=False)
    op.alter_column('batches', 'batch_date',
               existing_type=sa.DATE(),
               comment='Дата производства партии',
               existing_nullable=False)
    op.alter_column('batches', 'nomenclature',
               existing_type=sa.VARCHAR(),
               comment="Что производим (например, 'Гайка М12')",
               existing_nullable=False)
    op.alter_column('batches', 'ekn_code',
               existing_type=sa.VARCHAR(),
               comment='Артикул / Внутренний код номенклатуры завода',
               existing_nullable=False)
    op.alter_column('batches', 'shift_start',
               existing_type=postgresql.TIMESTAMP(),
               comment='Во сколько смена началась',
               existing_nullable=False)
    op.alter_column('batches', 'shift_end',
               existing_type=postgresql.TIMESTAMP(),
               comment='Во сколько смена должна закончиться',
               existing_nullable=False)
    op.alter_column('batches', 'work_center_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на станок: на каком оборудовании это делается',
               existing_nullable=False)
    op.drop_column('batches', 'updated_at')
    op.drop_column('batches', 'created_at')
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment='Внутренний ID детали',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'unique_code',
               existing_type=sa.VARCHAR(),
               comment='Тот самый СЕРИЙНЫЙ НОМЕР (уникальный штрихкод, RFID, QR-код детали)',
               existing_nullable=False)
    op.alter_column('products', 'batch_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на сменное задание: в рамках какой партии создана эта деталь',
               existing_nullable=False)
    op.alter_column('products', 'is_aggregated',
               existing_type=sa.BOOLEAN(),
               comment='Участвовала ли эта деталь в массовой агрегации (наша Celery-таска)',
               existing_nullable=False)
    op.alter_column('products', 'aggregated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Когда именно деталь была сагрегирована',
               existing_nullable=True)
    op.alter_column('work_centers', 'id',
               existing_type=sa.INTEGER(),
               comment='Внутренний ID станка в базе',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('work_centers', 'identifier',
               existing_type=sa.VARCHAR(),
               comment="Заводской шифр станка (например, 'ЛЕНТА-01')",
               existing_nullable=False)
    op.alter_column('work_centers', 'name',
               existing_type=sa.VARCHAR(),
               comment="Понятное название (например, 'Конвейер сборки')",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_centers', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Понятное название (например, 'Конвейер сборки')",
               existing_nullable=False)
    op.alter_column('work_centers', 'identifier',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Заводской шифр станка (например, 'ЛЕНТА-01')",
               existing_nullable=False)
    op.alter_column('work_centers', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Внутренний ID станка в базе',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'aggregated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Когда именно деталь была сагрегирована',
               existing_nullable=True)
    op.alter_column('products', 'is_aggregated',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Участвовала ли эта деталь в массовой агрегации (наша Celery-таска)',
               existing_nullable=False)
    op.alter_column('products', 'batch_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на сменное задание: в рамках какой партии создана эта деталь',
               existing_nullable=False)
    op.alter_column('products', 'unique_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Тот самый СЕРИЙНЫЙ НОМЕР (уникальный штрихкод, RFID, QR-код детали)',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Внутренний ID детали',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('batches', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('batches', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('batches', 'work_center_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на станок: на каком оборудовании это делается',
               existing_nullable=False)
    op.alter_column('batches', 'shift_end',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Во сколько смена должна закончиться',
               existing_nullable=False)
    op.alter_column('batches', 'shift_start',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Во сколько смена началась',
               existing_nullable=False)
    op.alter_column('batches', 'ekn_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Артикул / Внутренний код номенклатуры завода',
               existing_nullable=False)
    op.alter_column('batches', 'nomenclature',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Что производим (например, 'Гайка М12')",
               existing_nullable=False)
    op.alter_column('batches', 'batch_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата производства партии',
               existing_nullable=False)
    op.alter_column('batches', 'batch_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Производственный номер партии (как в 1С или на бумаге)',
               existing_nullable=False)
    op.alter_column('batches', 'team',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Кто выполняет работу (например, 'Бригада 1')",
               existing_nullable=False)
    op.alter_column('batches', 'shift',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Название или номер смены (например, 'Ночная' или 'Смена 1')",
               existing_nullable=False)
    op.alter_column('batches', 'task_description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Текстовое описание: что именно нужно сделать',
               existing_nullable=False)
    op.alter_column('batches', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Точное время, когда партию завершили',
               existing_nullable=True)
    op.alter_column('batches', 'is_closed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Статус задания: False - в работе, True - завершено',
               existing_nullable=False)
    op.alter_column('batches', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Внутренний ID партии (технический)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
